### ISSUE TITLE
Add objectParam

### ISSUE THREAD

**Issue by Airblader** [TNG/ngqp#119]
**What's your idea?**

We have stringParam, booleanParam etc. It would be good to add `objectParam` which by default uses JSON stringify/parse for (de-)serialization.

**Comment by alexey-anufriev** [comment]
But how would that be represented in URL? `http://my-site.com/index.html?objParam={a:1,b:2}`?

**Comment by Airblader** [comment]
Yeah, plus any URL encoding that is done to it. This may seem odd – and for me it is – but the Angular router does JSON stringify by default for query parameters when necessary while ngqp requires an explicit serializer.

I think we don't need to be opionated here given how trivial supporting this would be. :-)

**Comment by Airblader** [comment]
I've somewhat changed my mind, for now anyway. For this to be useful and "complete" we would have to provide a smarter compareWith function, but I would sort of like to avoid being opionated about its implementation. So I'll close this for now.
