### ISSUE TITLE
Update to support Angular 13

### ISSUE THREAD

**Issue by w5l** [TNG/ngqp#204]
**What's your idea?**

Update support to recent Angular versions, at least Angular 13 and when possible also upcoming 14.

**Describe the solution you'd like**

Please update [`package.json`](https://github.com/TNG/ngqp/blob/master/projects/ngqp/core/package.json#L26-L29) to include newer versions in the allowed range.

We've been using NGQP with Angular 13 (using `npm --force` to ignore warnings) without issues for a while now. I think this change can be done safely. Not sure about 14.

**Comment by Airblader** [comment]
Thanks, @w5l. I'll try to make this happen soon!

**Comment by Airblader** [comment]
Thanks again, @w5l for bringing this up and also letting me know about having used it with v13 already. I've released [a new 13.0.0 version on npm](https://www.npmjs.com/package/@ngqp/core/v/13.0.0) now! Let me know if there are any issues.

For v14, I'd like to wait for that to be released; please don't hesitate to open another issue once it is released should ngqp not have released yet, and I'll do my best to address it quickly.
