### ISSUE TITLE
'QueryParamModule' does not appear to be an NgModule class

### ISSUE THREAD

**Issue by EvansMatthew97** [TNG/ngqp#222]
Hello. I'm having trouble adding the library to my project:
![image](https://user-images.githubusercontent.com/10000036/189339796-5d18e657-5bc2-4901-a082-aefab052056b.png)

I have tried a manual installation, which did install the module:
![image](https://user-images.githubusercontent.com/10000036/189340034-459185ab-bd59-4630-800f-1d775df833e0.png)

But if I try to import the module I just see the following error:
```
'QueryParamModule' does not appear to be an NgModule class.(-996002)
query-param.module.d.ts(4, 3): This likely means that the library (@ngqp/core) which declares QueryParamModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

I think it's failing because ngcc needs to be run (?) but I'm not sure how to run it manually. Has anyone experienced the same issue? I have used this library successfully on a previous Angular project.

Thank you.

**Comment by Airblader** [comment]
What Angular version are you using? Can you try installing the package without ng add and manually importing it into the app?

**Comment by EvansMatthew97** [comment]
I'm using the following @angular dependency versions:
![image](https://user-images.githubusercontent.com/10000036/189343597-953b936f-1c79-4866-bfc1-bbcf849049c6.png)

I just got it to work by doing the following:
```bash
$ rm -rf node_modules
$ pnpm install
$ pnpm run build
```

I previously tried re-running `pnpm run build` but it didn't recompile any modules - removing the `node_modules` folder was required. Maybe this is a caching/hook issue with `pnpm`?

**Comment by Airblader** [comment]
Maybe it had to do with `ng add` somehow. We used to support `ng add` with automatically importing the module, but eventually removed that. I'm glad you got it to work now. I assume we can close this issue then?

**Comment by EvansMatthew97** [comment]
Yes we can close the issue. I might re-open if I encounter any problems with pipeline builds, but it seems to work fine so long as node_modules is not present initially.

Thank you
