### ISSUE TITLE
Support standalone parameters

### ISSUE THREAD

**Issue by Airblader** [TNG/ngqp#61]
**What's your idea?**
Currently, we require there to be a parent QueryParamGroup in order to bind any QueryParam to a component. If one wants to sync only a single parameter, this is a bit verbose. We could maybe support binding a single parameter without a group.

**Describe the solution you'd like**
We could allow something like

```html
<app-component queryParamName="param" [queryParamOptions]="{standalone: true}"></app-component>
```

**Additional context**
A necessary precondition for this feature is #51.

**Alternative Idea**
We could instead just allow binding the group on the same component:

```html
<app-component queryParamName="param" [queryParamGroup]="paramGroup"></app-component>
```

This would be much easier to implement (probably just remove some `@SkipSelf()`), but would still require the user to set up an entire group.

**Comment by Airblader** [comment]
I think the latter is probably already possible now, though I haven't verified it.

**Comment by Airblader** [comment]
So the idea of `[queryParam]` for standalone is solid, I think. However, upon some further inspection I think there's some issues with the event propagation that maybe we should tackle first.

**Comment by alexey-anufriev** [comment]
Ok, will switch back to this issue as soon as #67 is done.
