### ISSUE TITLE
Provide a ControlValueAccessor for mat-select from @angular/material

### ISSUE THREAD

**Issue by Airblader** [TNG/ngqp#94]
**What's your idea?**

Unfortunately, `mat-select` does not provide a ControlValueAccessor but uses another mechanism instead (see https://github.com/angular/material2/issues/6549). Given the popularity of the library, we should consider providing our own implementation for it similar to what @MrWolfZ did here:

https://github.com/MrWolfZ/ngrx-forms/blob/dd557704f5bf99576827ad790a8d4680f40ecb0c/example-app/src/app/material/mat-select-view-adapter.ts#L17

For completeness sake it should be mentioned that this can also be achied using our `ControlValueAccessorDirective` (at least in my quick tests with static options it worked fine).

We should probably do this in a separate package and adapt the schematics to detect if @angular/material is installed and then also install this package.

**Describe the solution you'd like**

A version adapted to our needs:

```
import { AfterViewInit, Directive, forwardRef, OnDestroy } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { MatSelect } from '@angular/material';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Directive({
  selector: 'mat-select[queryParamName], mat-select[queryParam]',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => MatSelectAccessorDirective),
      multi: true,
    },
  ],
})
export class MatSelectAccessorDirective implements ControlValueAccessor, AfterViewInit, OnDestroy {

  private value: unknown;
  private readonly destroy$ = new Subject<void>();

  constructor(private matSelect: MatSelect) {
  }

  public ngAfterViewInit(): void {
    this.matSelect.options.changes.pipe(
      takeUntil(this.destroy$)
    ).subscribe(() => Promise.resolve().then(() => this.matSelect.writeValue(this.value)));
  }

  public ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  public registerOnChange(fn: any): void {
    this.matSelect.registerOnChange(value => {
      this.value = value;
      fn(value);
    });
  }

  public registerOnTouched(fn: any): void {
    this.matSelect.registerOnTouched(fn);
  }

  public setDisabledState(isDisabled: boolean): void {
    this.matSelect.setDisabledState(isDisabled);
  }

  public writeValue(value: unknown): void {
    this.value = value;

    const selectedOption = this.matSelect.selected;

    if (selectedOption) {
      if (Array.isArray(selectedOption) && Array.isArray(value)) {
        if (value.length === selectedOption.length && value.every((v, i) => v === selectedOption[ i ])) {
          return;
        }
      } else if (!Array.isArray(selectedOption)) {
        if (value === selectedOption.value) {
          return;
        }
      }
    }

    setTimeout(() => this.matSelect.writeValue(value), 0);
  }

}
```

**Comment by Airblader** [comment]
Having given it some more thought I'm not comfortable, for the moment, with maintaining such an addition. It feels like more of a hack and @angular/material should just expose the CVA, I think. If someone needs to use ngqp with mat-select they can copy the directive above into their project.

**Comment by broweratcognitecdotcom** [comment]
Just a question about your directive above... what is 'unknown' in the writeValue function?

public writeValue(value: **unknown**): void {

**Comment by Airblader** [comment]
@broweratcognitecdotcom It's a type in TypeScript, see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type.

> Also, can you show the usage of the directive?

You don't need to explicitly use it, just add the directive to your code and some module and it will apply automatically. :-)

**Comment by broweratcognitecdotcom** [comment]
Ok. But I am getting: ERROR TypeError: this.getQueryParamGroup(...)._registerOnChange is not a function.

My code:

createParamGroup() {
    this.paramGroup = this.queryParamBuilder.group({
      zone_id: this.queryParamBuilder.stringParam('zone_id', {emptyOn: this.prefs.filters.zone_id ? this.prefs.filters.zone_id : this.zones[0]}),
    });
  }

template:

<mat-form-field appearance="fill" class="">
            <mat-label>{{'@cognitec/fvv-visits/VisitsTimeMachineComponent/Zone' | translate}}</mat-label>
            <mat-select queryParamGroup="zone_id" disableOptionCentering="true">
              <mat-option *ngFor="let zone of zones" [value]="zone">{{zone}}</mat-option>
            </mat-select>
        </mat-form-field>

**Comment by Airblader** [comment]
How are you using `paramGroup` in the template?

**Comment by Raphyyy** [comment]
Hello @Airblader and thanks for your work
Do the snippet you provided above is still up to date to use ?
I would like to use ngqp along with mat-select. I tried your directive and I am facing this error on value change : 
```
Uncaught TypeError: (value || []).map is not a function
    at MultiQueryParam.serializeValue (ngqp-core.js:283)
    at ngqp-core.js:858
    at Array.map (<anonymous>)
    at QueryParamGroupService.getParamsForValue (ngqp-core.js:856)
    at MapSubscriber.project (ngqp-core.js:702)
    at MapSubscriber._next (map.js:29)
    at MapSubscriber.next (Subscriber.js:49)
    at FilterSubscriber._next (filter.js:33)
    at FilterSubscriber.next (Subscriber.js:49)
    at ZipSubscriber.checkIterators (zip.js:96)
```
